### ISSUE TITLE
Add the vispubdata dataset as a default 

### ISSUE THREAD

**Issue by john-guerra** [john-guerra/shipyard#15]
Also, we need a loading indicator...

**Comment by jgmurillo10** [comment]
Loading indicator will be on the next release
![image](https://user-images.githubusercontent.com/16781872/54831622-accead80-4c88-11e9-885b-4458c3269461.png)

**Comment by jgmurillo10** [comment]
Fixed on https://github.com/john-guerra/shipyard/commit/bc373989e82530c37e7192bec01ac553e1b55182 including the loading indicator
