### ISSUE TITLE
Table isn't loading properly

### ISSUE THREAD

**Issue by john-guerra** [john-guerra/shipyard#2]
The table loads with each column using the whole width. No way one could see anything there...

**Comment by jgmurillo10** [comment]
There was a CSS rule that was overwriting the `display` property for some elements just in production. Deployed with fix.
https://john-guerra.github.io/shipyard/

**Comment by jgmurillo10** [comment]
Update table styles to show side by side with navio.

**Comment by jgmurillo10** [comment]
Fixed by 05c1956
